/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VenuesRouteImport } from './routes/venues'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SaferGamblingRouteImport } from './routes/safer-gambling'
import { Route as PromotionsRouteImport } from './routes/promotions'
import { Route as GamesRouteImport } from './routes/games'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VenuesSlugRouteImport } from './routes/venues.$slug'

const VenuesRoute = VenuesRouteImport.update({
  id: '/venues',
  path: '/venues',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SaferGamblingRoute = SaferGamblingRouteImport.update({
  id: '/safer-gambling',
  path: '/safer-gambling',
  getParentRoute: () => rootRouteImport,
} as any)
const PromotionsRoute = PromotionsRouteImport.update({
  id: '/promotions',
  path: '/promotions',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesRoute = GamesRouteImport.update({
  id: '/games',
  path: '/games',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VenuesSlugRoute = VenuesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => VenuesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/games': typeof GamesRoute
  '/promotions': typeof PromotionsRoute
  '/safer-gambling': typeof SaferGamblingRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/venues': typeof VenuesRouteWithChildren
  '/venues/$slug': typeof VenuesSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/games': typeof GamesRoute
  '/promotions': typeof PromotionsRoute
  '/safer-gambling': typeof SaferGamblingRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/venues': typeof VenuesRouteWithChildren
  '/venues/$slug': typeof VenuesSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/games': typeof GamesRoute
  '/promotions': typeof PromotionsRoute
  '/safer-gambling': typeof SaferGamblingRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/venues': typeof VenuesRouteWithChildren
  '/venues/$slug': typeof VenuesSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/faq'
    | '/games'
    | '/promotions'
    | '/safer-gambling'
    | '/sitemap.xml'
    | '/venues'
    | '/venues/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/faq'
    | '/games'
    | '/promotions'
    | '/safer-gambling'
    | '/sitemap.xml'
    | '/venues'
    | '/venues/$slug'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/faq'
    | '/games'
    | '/promotions'
    | '/safer-gambling'
    | '/sitemap.xml'
    | '/venues'
    | '/venues/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  FaqRoute: typeof FaqRoute
  GamesRoute: typeof GamesRoute
  PromotionsRoute: typeof PromotionsRoute
  SaferGamblingRoute: typeof SaferGamblingRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  VenuesRoute: typeof VenuesRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/venues': {
      id: '/venues'
      path: '/venues'
      fullPath: '/venues'
      preLoaderRoute: typeof VenuesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/safer-gambling': {
      id: '/safer-gambling'
      path: '/safer-gambling'
      fullPath: '/safer-gambling'
      preLoaderRoute: typeof SaferGamblingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/promotions': {
      id: '/promotions'
      path: '/promotions'
      fullPath: '/promotions'
      preLoaderRoute: typeof PromotionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games': {
      id: '/games'
      path: '/games'
      fullPath: '/games'
      preLoaderRoute: typeof GamesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/venues/$slug': {
      id: '/venues/$slug'
      path: '/$slug'
      fullPath: '/venues/$slug'
      preLoaderRoute: typeof VenuesSlugRouteImport
      parentRoute: typeof VenuesRoute
    }
  }
}

interface VenuesRouteChildren {
  VenuesSlugRoute: typeof VenuesSlugRoute
}

const VenuesRouteChildren: VenuesRouteChildren = {
  VenuesSlugRoute: VenuesSlugRoute,
}

const VenuesRouteWithChildren =
  VenuesRoute._addFileChildren(VenuesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  FaqRoute: FaqRoute,
  GamesRoute: GamesRoute,
  PromotionsRoute: PromotionsRoute,
  SaferGamblingRoute: SaferGamblingRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  VenuesRoute: VenuesRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
